language: php

sudo: false

php:
    - 5.4
    - 5.5
    - 5.6

before_script:
    - composer install --prefer-source
    - echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script: './vendor/bin/phpunit --coverage-text && ./vendor/bin/behat -f progress'
